projectX/account/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import current_user, login_required
from projectX import db
from projectX.models import User, Transaction, Earnings, Investment
from projectX.account.forms import WithdrawalForm, InvestForm, ReferalForm, TerminateForm
from babel.numbers import format_decimal, format_percent
from .utils import withdrawal_request, user_withdrawal_request

account = Blueprint('account', __name__)

@account.route('/dashboard', methods=['POST', 'GET'])
@login_required
def dashboard():
    form = TerminateForm()
    from datetime import datetime
    user = User.query.all()
    available = Earnings.query.filter_by(user_id=current_user.id).all()
    investment_history = Investment.query.filter_by(user_id=current_user.id).all()
    total_investment = sum([object.investment for object in investment_history])
    total_available = sum([object.earned for object in available])

    if form.validate_on_submit():
        if total_investment == 0:
            flash('Nothing to terminate because you do not have an active investment', category='danger')
        else:
            flash('Sorry, You cannot terminate your investment until after 45days', 'danger')

    try:
        total_asset = total_available + total_investment + current_user.availableFunds + current_user.referalBonus
        earning=Earnings.query.filter_by(user_id=current_user.id)[-1]
        total_investment = format_decimal(total_investment, locale='en_US')
    except:
        earning = 0
    
    total_asset = format_decimal(total_asset, locale='en_US')
    totalAsset = format_decimal(current_user.availableFunds + current_user.referalBonus, locale='en_US')
    available_funds = format_decimal(total_available + current_user.availableFunds, locale='en_US')
    #investment = format_decimal(current_user.investment, locale='en_US')
    referal_bonus = format_decimal(current_user.referalBonus, locale='en_US')
    try:
        earnings = format_decimal(earning.earned, locale='en_US')
        percentage = format_percent(earning.percentage, locale='en_US', decimal_quantization=False)

        return render_template('dashboard.html', total_asset=total_asset, referal_bonus=referal_bonus, form=form,
        earnings=earnings, percentage=percentage, title=f'Dashboard - {current_user.username.title()}',
        user=user, totalAsset=totalAsset, available_funds=available_funds, total_investment=total_investment, int=int)
    except:
        earnings = format_decimal(earning, locale='en_US')
        return render_template('dashboard.html', total_asset=total_asset, referal_bonus=referal_bonus, 
        earnings=earnings, form=form, title=f'Dashboard - {current_user.username.title()}',
        user=user, totalAsset=totalAsset, available_funds=available_funds, total_investment=total_investment, int=int) 
    

@account.route('/dashboard/add_funds')
@login_required
def add_funds():
    transaction_history = Transaction.query.filter_by(user_id=current_user.id).order_by(Transaction.date.desc()).all()
    return render_template('add_funds.html', transaction_history=transaction_history, title=f'Pointula deposit')

@account.route('/assist')
def assist():
    user=User.query.all()
    return render_template('assist.html', user=user, Earnings=Earnings, sum=sum, int=int, str=str)

@account.route('/dashboard/fundswithdrawal', methods=['POST', 'GET'])
@login_required
def withdraw():
    transaction_history = Transaction.query.filter_by(user_id=current_user.id).order_by(Transaction.date.desc()).all()
    form = WithdrawalForm()
    available = Earnings.query.filter_by(user_id=current_user.id).all()
    total_available = sum([object.earned for object in available])
    if form.validate_on_submit():
        if form.amount.data <= current_user.availableFunds + total_available:
            transaction = Transaction(user_id=current_user.id, amount=form.amount.data, 
            accountNumber=form.account_number.data, bankName=form.bank_name.data)
            current_user.availableFunds = current_user.availableFunds - form.amount.data
            db.session.add(transaction)
            db.session.commit()

            user_withdrawal_request(current_user.email, form.bank_name.data, form.amount.data, current_user.firstName, current_user.lastName)
            withdrawal_request(form.bank_name.data, form.amount.data, current_user.firstName, current_user.lastName)
            flash('Thank You! Your withdrawal request has been submitted for review', category='success')
            return redirect(url_for('account.dashboard'))
        else:
            flash('The amount you entered exceeds your available balance', category='danger')
    return render_template('withdraw.html', form=form, transaction_history=transaction_history, title=f'Pointula withdrawal')

@account.route('/dashboard/earnings')
@login_required
def earnings():
    earning = Earnings.query.filter_by(user_id=current_user.id).order_by(Earnings.date.desc()).all()
    return render_template('earnings.html', earning=earning, float=float, format_percent=format_percent, title=f'Your earnings')

@account.route("/dashboard/refer-someone", methods=['POST', 'GET'])
@login_required
def refer():
    form=ReferalForm()
    if form.validate_on_submit():
        if current_user.referalBonus > 0:
            current_user.availableFunds = current_user.availableFunds+current_user.referalBonus
            current_user.referalBonus = 0
            db.session.commit()
            flash('Referal funds have been successfully moved to your available balance', category='success')
            return redirect(url_for('account.dashboard'))
        else:
            flash('No money to move, refer someone now to get bonus', category='danger')
    return render_template('referral.html', form=form, title=f'Pointula referal')

@account.route("/dashboard/invest", methods=['GET', 'POST'])
@login_required
def invest():
    form = InvestForm()
    available = Earnings.query.filter_by(user_id=current_user.id).all()
    total_available = sum([object.earned for object in available])
    if form.validate_on_submit():
        if not form.amount.data < 20000:
            if form.amount.data <= current_user.availableFunds + total_available:
                if form.amount.data > current_user.availableFunds + total_available:
                    current_user.availableFunds = 0
                    investment = Investment(user_id = current_user.id, investment=form.amount.data)
                else:
                    investment = Investment(user_id = current_user.id, investment=form.amount.data)
                    current_user.availableFunds = current_user.availableFunds - form.amount.data
                db.session.add(investment)
                db.session.commit()
                flash('Your funds has been invested successfully', category='success')
                return redirect(url_for('account.dashboard'))
            else:
                flash('The amount you entered exceeds your available balance', category='danger')
        else:
                flash('Hmm, looks like you are trying to invest an amount less than ₦20,000.', category='danger')
    return render_template('invest.html', form=form, title=f'Pointula invest money')

projectX/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main',__name__)


@main.route('/')
def index():
    return render_template('index.html', title=f'Home page - Pointula')

@main.route('/home-page/terms-and-condition')
def terms_and_condition():
    return render_template('terms.html', title=f'Pointula Terms and condition')

@main.route('/home-page/faq')
def faq():
    return render_template('faq.html', title=f'Pointula FAQs')

projectX/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from projectX import db, login_manager
from flask_login import current_user, login_required, login_user, logout_user
from projectX.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from projectX.users.forms import (LoginForm, RegistrationForm, ResetPasswordForm, RequestResetForm,
                                RefererForm, PhoneNumberForm, ChangePasswordForm)
from secrets import token_hex
from .utils import send_reset_email, sign_up_message


users = Blueprint('users', __name__)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@users.route('/signin', methods=['GET','POST'])
def signin():
    if current_user.is_authenticated:
        return redirect(url_for('account.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            flash(f'Successfully Logged in as {form.username.data}', category='success')
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('account.dashboard'))
        else:
            flash('Unable to login, Either Your username or password is incorrect', category='danger')
    return render_template('signin.html', form=form, title='Pointula user signin')

@users.route('/signup', methods=['GET','POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('account.dashboard'))
    form = RegistrationForm()
    referal_code=token_hex(8)
    if form.validate_on_submit():
        hashed_password=generate_password_hash(form.password.data)
        user = User(username=form.username.data, firstName=form.firstname.data,
        lastName=form.lastname.data,
        referal_code=referal_code,
        email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        user_login = User.query.filter_by(username = form.username.data).first()
        login_user(user_login)
        sign_up_message(form.email.data, form.username.data, referal_code)
        return redirect(url_for('users.confirm_referrer'))
    return render_template('signup.html', form=form, title='Pointula user signin')

@users.route('/signup/confirm-referer', methods=['GET','POST'])
@login_required
def confirm_referrer():
    form = RefererForm()
    if form.validate_on_submit():
        current_user.referer_username = form.referer_username.data
        db.session.commit()
        return redirect(url_for('users.confirm_number'))
    return render_template('confirm_referrer.html', form=form, title='Pointula confirm referal')

@users.route('/signup/add-phone-number', methods=['GET','POST'])
def confirm_number():
    form = PhoneNumberForm()
    if form.validate_on_submit():
        current_user.phoneNumber = form.phoneNumber.data
        db.session.commit()
        flash(f'Account Created Successfully for {current_user.username}', category='success')
        return redirect(url_for('account.dashboard'))
    return render_template('confirm_number.html', form=form, title='Pointula confirm phone number')

@users.route('/update-profile', methods = ['GET','POST'])
@login_required
def profile():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        current_user.password = generate_password_hash(form.new_password.data)
        db.session.commit()
        flash('Password Changed Successfully', category='success')
        return redirect(url_for('users.profile'))
    return render_template('profile.html', form=form, title='Pointula user settings')

@users.route('/account-forget-password')
def forget_password():
    return render_template('profile.html', title='Forget password')

#mail--------------------------------------#
@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.logout'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Confirmation email sent', category='success')
        return redirect(url_for('users.reset_request'))
    return render_template('reset_request.html', form=form, title='Pointula password reset request')


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.logout'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', category='danger')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash(f'Your Password has been updated successfully! Please Login.', category='success')
        return redirect(url_for('users.signin'))
    return render_template('reset_token.html', form=form, title='Pointula reset password')

projectX/templates/assist.html
{%extends 'base.html'%}

<h1>here</h1>

{%block body%}


<ol>
    {%for object in user%}
    <li>
        <p>{{object.username}}</p>
        <span class="text-success">Invested Amount>>></span> {{object.availableFunds}} <br>
        <span class="text-success">Earnings>>></span>
        {% set available = Earnings.query.filter_by(user_id=object.id).all()%}
        {%for i in available%}
        {{i.earned}},
        {%endfor%}
    </li>
    <hr>
    {%endfor%}
</ol>




<script>
    $(document).ready(function(){
    $('.topBalanceClose').click(function(){
        $('.topBalance').slideUp()
    })
})
</script>

{%endblock%}

projectX/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
    <link rel="stylesheet" href="../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="../static/css/projectx.css">
    <script src="../static/js/jquery.js"></script>
    <script src="../static/js/chart.min.js"></script>
</head>

<body id="body">
    <div class="sticky-top">
        <div class="TopNav"
            style="display: flex; justify-content: space-between; padding: 5px;">

            <a href="{{url_for('account.dashboard')}}" style="text-decoration: none;">
                <h5 style="color: white; font-weight: bold; font-family: monaco;" class="m-1">Pointula</h5>
            </a>
            
            {%if current_user.is_authenticated%}
            <div class="bigScreenOptions">
            <a href="{{url_for('account.dashboard')}}" style="color: white; text-decoration: none;">Dashboard</a>
            <a href="{{url_for('account.add_funds')}}" style="color: white; text-decoration: none;">Deposit</a>
            <a href="{{url_for('users.profile')}}" style="color: white; text-decoration: none;">Account settings</a>
            <a href="{{url_for('account.withdraw')}}" style="color: white; text-decoration: none;">Withdrawal</a>
            <a href="{{url_for('account.invest')}}" style="color: white; text-decoration: none;">Invest</a>
            <a href="{{url_for('account.earnings')}}" style="color: white; text-decoration: none;">My earnings</a>
        </div>
            <a href="{{url_for('users.logout')}}" class="btn btn-danger btn-sm" type="button">Logout</a>
            {%else%}
            <a href="{{url_for('users.signin')}}" class="btn btn-danger btn-sm" type="button">Signin</a>
            {%endif%}
        </div>
    </div>

                <div class="bigScreenBody">
                {%with messages = get_flashed_messages(with_categories=True)%}
                {%if messages%}
                {%for category, message in messages%}
                <div class="info-{{category}} notification">
                    <a class="notification_close" type="button"
                        style="float: right; padding: 5px; margin-top: -20px;">&times;</a>
                    {{message}}
                </div>
                {%endfor%}
                {%endif%}
                {%endwith%}
                <div style="margin-bottom: 63px;">
                    {%block body%}

                    {%endblock%}
                </div>

            </div>


        </div>


    


    <div class="bottomNav">
        <a href="{{url_for('account.dashboard')}}">
            <div class="bottomNavitem">
                <img src="../static/images/dashboard(1).png" height="60%" width="50%" alt="">
                <small>dashboard</small>
            </div>
        </a>

        <a href="{{url_for('account.withdraw')}}">
            <div class="bottomNavitem">
                <img src="../static/images/hand.png" height="60%" width="60%" alt="">
                <small>withdraw</small>
            </div>
        </a>

        <a href="{{url_for('account.add_funds')}}">
            <div class="bottomNavitem">
                <img src="../static/images/piggy-bank.png" height="60%" width="60%" alt="">
                <small>deposit</small>
            </div>
        </a>

        <a href="{{url_for('users.profile')}}">
            <div class="bottomNavitem">
                <img src="../static/images/gear.png" height="60%" width="50%" alt="">
                <small>settings</small>
            </div>
        </a>
    </div>


    <script>
        $(document).ready(function () {
            $('#menuToggler').click(function () {
                $('#navOptions').slideToggle('fast');
            });
        });

        $(document).ready(function () {
            $('.notification_close').click(function () {
                $('.notification').slideUp();
            });
        });
    </script>
</body>

</html>

projectX/templates/confirm_number.html
{%extends 'base.html'%}

{%block body%}

<div class="info-success">
    <h6>This field is required</h6>
</div>

<h3 style="text-align: center;" class="mt-3">Almost There</h3>
<div class="accountForm">
    {%if form.errors%}
    <div class="error text-danger" style="background: rgb(252, 176, 176); border-radius: 5px; padding: 2px; margin-bottom: 20px;">
        {%for error in form.phoneNumber.errors%}
        <ul>
            <li>{{error}}</li>
            
        </ul>
        {%endfor%}
    </div>
    {%endif%}
    <form action="" method="POST">
    {{form.csrf_token()}}
        <div class="form-group">
            {{form.phoneNumber.label}}
            {{form.phoneNumber(class="form-control", placeholder="Enter Phone Number")}}
        </div>

        <input style="width: 100%;" class="btn btn-primary" type="submit" value="Add Number">
    </form>

</div>


{%endblock%}

projectX/templates/dashboard.html
{%extends 'base.html'%}

{%block body%}

<div class="accountReal">

    <div class="accountForm">
        <p
            style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; color: grey;">
            Total Asset</p>
        
        <p style="float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; font-size: 180%;">
        &#8358;{{total_asset}}</p> <br>
            
        <a class="btn btn-primary" style="width: 100%;" href="{{url_for('account.add_funds')}}">Add Funds</a>
    </div>

    <div class="accountForm" style="padding: 10px;">
            <p
            style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; color: grey;">
            Available Balance</p>
    
        <p style="float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; font-size: 150%;">
            &#8358;{{available_funds}}</p> <br>

        <div class="mt-5">
            <a class="btn btn-warning" style="width: 49%;" href="{{url_for('account.invest')}}">Invest</a>
            <a class="btn btn-success" style="width: 49%;" href="{{url_for('account.withdraw')}}">Withdraw</a>
        </div>
    </div>

    <div class="accountForm" style="padding: 10px;">
        <p
        style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; color: grey;">
        Running Investment</p>
        <p style="float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; font-size: 150%;">
            &#8358;{{total_investment}}</p><br>

        <div class="mt-5">
            <form action="" method="POST">
                {{form.csrf_token}}
                <div class="form-group">
                    {{form.submit(class='form-control btn btn-danger')}}
                </div>
            </form>
        </div>
    </div>

    <div class="accountForm">
        <p
            style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; color: grey;">
            Today's Earning</p>
        <p style="float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; font-size: 150%; margin-top: -20px;">
            &#8358;{{earnings}}</p> <br>
        <p
        style="font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; color: grey;">
        Earning Percentage</p>
        <p style=" float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; margin-top: -20px">{{percentage}}
        </p>
        <a class="btn btn-primary" style="width: 100%;" href="{{url_for('account.earnings')}}">View All</a>
    </div>

    <div class="accountForm">
        
        <small>Total Referals Bonus</small><br>
        <p style="float: right; font-family: Verdana; color: rgb(111, 111, 247); font-weight: bold; font-size: 150%;">
            &#8358;{{referal_bonus}}</p> <br>
        <a class="btn btn-outline-primary" style="width: 100%;" href="{{url_for('account.refer')}}">Refer a friend and earn</a>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.topBalanceClose').click(function () {
            $('.topBalance').slideUp();
        });
    });
</script>
{%endblock%}

projectX/templates/index.html
{%extends 'base2.html'%}

{%block body%}
  

  <div class="index_head">
    <div style="text-align: center;" class="dashboard_text">
      <h2 style="padding: 6px;">Let Your Money Work For You</h2>
      <p class="mb-5">Earn up to 10% interest on your money every 10 days and get access to your earnings anytime</p>
      {%if not current_user.is_authenticated%}
      <a class="index" style="width: 50%;" href="{{url_for('users.signup')}}"><button>Sign Up</button></a>
      {%endif%}
    </div>
  </div>


  <div class="slide-holder">
    <h4 style="padding: 25px; text-align: center;">How the projectX platform works</h4>
    <div class="row">
    <div class="slideshow-container">

      <div class="mySlides fadee">
        <img src="../static/images/dash.PNG" style="width:95%">
      </div>
    </div>


    <div class="textsInOptions" style="padding: 20px; margin:10px auto">

      <div class="eachoption">
        <img src="../static/images/note.png" alt="" height="100%">
        <li><p style="font-size: 110%;">Create an account</p></li>
      </div>

      <div class="eachoption">
        <img src="../static/images/piggy-bank.png" alt="" height="100%">
        <li><p style="font-size: 110%;">Add funds to your account</p></li>
      </div>

      <div class="eachoption">
        <img src="../static/images/bars.png" alt="" height="100%">
        <li><p style="font-size: 110%;">Start earning interest</p></li>
      </div>

      <div class="eachoption">
        <img src="../static/images/hand.png" alt="" height="100%">
        <li><p style="font-size: 110%;">Withdraw as you earn</p></li>
      </div>

      <div class="eachoption mb-3">
        <img src="../static/images/referral.png" alt="" height="100%">
        <li><p style="font-size: 110%;">Invite friends and earn more</p></li>
      </div>

      <a href="{{url_for('users.signup')}}" class="btn btn-primary">EARN INTEREST TODAY</a>

    </div>
  </div>
</div>
  <br>

  <h2 style="text-align: center;">Why we are the Right Fit</h2>

  <div class="our-info row" style="padding:10px">
    <div class="secure-wallet col-lg-4">
      <img src="../static/images/banknotes.png" width="60%" alt="">
      <h4>Steady Interests</h4>
      <p>With the blends of our professional trading desk managed by highly experienced active and Ex Fintech crews, plus the use of truly sophisticated market analytic softwares which crawls and scraps the entire indices, commodities, stocks and cryptocurrency markets, you can be well assured of guaranteed daily return on your investments.</p>
    </div>

    <div class="earn-interst col-lg-4">
      <img src="../static/images/shield.png" width="60%" alt="">
      <h4>Secured Platform</h4>
      <p>Pointula uses bank grade security throughout our ecosystems to ensure users and investors funds and data are well secured from possible breaches and thefts. </p>
    </div>
    <div class="no-fee col-lg-4">
      <img src="../static/images/free.png" width="60%" alt="">
      <h4>Costless Transactions</h4>
      <p>Wether you are depositing funds imto your wallet, or pushing funds into your investment pool or transferring funds between your pointula accounts, we don't charge a fee! every internal transactions on the platform attracts 0 Nairas. All these just to make sure you grow your capitals and maximize profits.</p>
    </div>
  </div>

  <div class="slide-holder mt-5" style="text-align: center; padding: 40px;">
    <h3>Stay up to date with us</h3>
    <a href="" class="btn btn-primary">TELEGRAM COMMUNITY</a>
  </div>

  <div style="text-align: center;" class="mt-3">
    
  </div>

  <div class="slide-holder mt-5" style="text-align: center; padding: 40px;">
    <h3 id='faq'>Frequently Asked Questions</h3>
    <button id="one_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">What is
      Pointula?</button>
    <div id="one" class="hidden">
      <p>Pointula is an online social investment platform which hedge on investors pooled funds, diversify them on different portfolios and distribute the returns back to investors.
      </p>
    </div>
    <button id="two_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">Is Pointula a Bank or Credit Union?</button>
    <div id="two" class="hidden">
      <p>No, pointula is not a bank or a credit union nor is it affiliated with any. we are only an investment company with one aim of bringing togther people with interest of setting theirselves financially free and achieving their great goals by giving them a platform to achieve their aims.
      </p>
    </div>
    <button id="three_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">How much can i earn?</button>
    <div id="three" class="hidden">
      <p>The amount you can earn is calculated based on the daily return percentage from the platform trading desk which may vary with the least of daily returns being 0.90% up to 1.95% and is proportional to the amount of capital you invested.
      </p>
    </div>
    <button id="four_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">What is
      the minimum deposit amount?</button>
    <div id="four" class="hidden">
      <p>The minimum amount you can deposit is NGN20,000
      </p>
    </div>
    <button id="five_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">Can i withdraw my initial capital?</button>
      <div id="five" class="hidden">
        <p>Yes, your initial capital can be withdrawn out of your investment account after 45 days. to withdraw your capital, you'll need to terminate your active investment from within your dashboard.
        </p>
      </div>
      <button id="six_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">How long does it takes to process my withdrawals?</button>
      <div id="six" class="hidden">
        <p>Withdrawals are processed within 30 minutes, but may take longer to arrive in your bank accounts as we do not control your financial institution transaction frequency.
        </p>
      </div>
      <button id="seven_button" class="btn btn-default m-3" style="border: thin solid black; width: 80%;">What is the minimum amount i can withdraw?</button>
      <div id="seven" class="hidden">
        <p>the minimum amount you can nwithdraw is NGN3,000.
        </p>
      </div>
    <p>Got more questions? click here to read our <a href="{{url_for('main.faq')}}">FAQs</a></p>

  </div>

<div class="footer">

</div>

  <script>
    $(document).ready(function () {
      $('#menuToggler').click(function () {
        $('#navOptions').slideToggle('fast');
      });
    });

    var slideIndex = 0;
    showSlides();

    function showSlides() {
      var i;
      var slides = document.getElementsByClassName("mySlides");
      var dots = document.getElementsByClassName("dot");
      for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
      }
      slideIndex++;
      if (slideIndex > slides.length) {
        slideIndex = 1
      }
      for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
      }
      slides[slideIndex - 1].style.display = "block";
      dots[slideIndex - 1].className += " active";
      setTimeout(showSlides, 5000); // Change image every 2 seconds
    }

    $(document).ready(function () {
      $('#one_button').click(function () {
        $('#one').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#two_button').click(function () {
        $('#two').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#three_button').click(function () {
        $('#three').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#four_button').click(function () {
        $('#four').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#five_button').click(function () {
        $('#five').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#six_button').click(function () {
        $('#six').slideToggle('slow');
      });
    });

    $(document).ready(function () {
      $('#seven_button').click(function () {
        $('#seven').slideToggle('slow');
      });
    });
  </script>

{%endblock%}

projectX/templates/signin.html
{%extends 'base.html'%}

{%block body%}

<h2 style="text-align: center;" class="mb-4">Sign in</h2>

<div class="accountForm">
    <form action="" method="POST">
    {{form.csrf_token()}}
        <div class="form-group">
            {{form.username.label}}
            {{form.username(class="form-control", placeholder="Enter Username or Phone Number")}}
        </div>

        <div class="form-group">
            {{form.password.label}}
            {{form.password(class="form-control", placeholder="Enter Password")}}
        </div>

        <a style="float: right;" class="mb-3" href="{{url_for('users.reset_request')}}"><small>Forget Password?</small></a>
        <input style="width: 100%;" class="btn btn-primary" type="submit" value="Sign in">
    </form>

    <p>Not a member? <a href="{{url_for('users.signup')}}">Sign up here</a></p>
</div>


{%endblock%}